# Standard library imports
import os
import sys
import shutil
import json
import glob
import threading
import configparser
from pathlib import Path
from contextlib import closing
import traceback

# Add the current directory to Python path
script_dir = os.path.dirname(os.path.abspath(__file__))
if script_dir not in sys.path:
    sys.path.append(script_dir)

# Third party libraries, may need to be installed manually
import gradio as gr
from PIL import Image

GradioBox = getattr(gr, "Box", gr.Group)

# Automatic1111 specific imports
from modules import script_callbacks, shared, sd_models, processing, images, sd_samplers

try:
    from modules import sd_schedulers
except ImportError:
    sd_schedulers = None

# Thumbnailizer script imports
from override_settings import load_override_settings, apply_override_settings, create_override_settings_template


def get_checkpoint_directory():
    ckpt_dir = getattr(shared.cmd_opts, "ckpt_dir", None)
    if ckpt_dir:
        return ckpt_dir

    ckpt_dirs = getattr(shared.cmd_opts, "ckpt_dirs", None)
    if ckpt_dirs:
        return ckpt_dirs[0]

    return sd_models.model_path


# Pre-initialization
ckpt_dir = get_checkpoint_directory() #string
script_dir = os.path.dirname(__file__) #string
user_sets_file_path = os.path.join(script_dir, 'sets_user.json') #string
user_blocklist_file_path = os.path.join(script_dir, 'blocklist_user.json') #string
# Check if sets_user.json exists, if it doesn't create it.
if not os.path.exists(user_sets_file_path):
    shutil.copy(os.path.join(script_dir, 'sets_template.json'), user_sets_file_path)
sets_file_path = os.path.join(script_dir, 'sets_user.json') #string
# Check if blocklist_user.json exists, if it doesn't create it.
if not os.path.exists(user_blocklist_file_path):
    shutil.copy(os.path.join(script_dir, 'blocklist_template.json'), user_blocklist_file_path)
model_blocklist_file_path = os.path.join(script_dir, 'blocklist_user.json') #string
if not os.path.exists(sets_file_path):
    print("Thumbnailizer Error: Unable to locate or create the sets_user.json file.")
if not os.path.exists(model_blocklist_file_path):
    print("Thumbnailizer Error: Unable to locate or create the blocklist_user.json file.")

# Load override settings
override_settings_file = os.path.join(script_dir, 'override_settings_user.txt')
if not os.path.exists(override_settings_file):
    create_override_settings_template(override_settings_file)
override_settings = load_override_settings(override_settings_file)

# Global variables
global current_set_name, current_suffix, gallery, blocked_paths, blocklist, set_data, all_model_names, all_model_paths, relevant_model_names, relevant_model_paths, data

# Configuration
current_set_name = "Default" #string
current_suffix = "" #string
blocklist = None #string
set_data = None # list of strings
all_model_names = [] #list of strings
all_model_paths = [] #list of strings
relevant_model_names = [] #list of strings
relevant_model_paths = [] #list of strings
gallery = None # Instance of gr.Gallery
gallery_height = 1000 #int
thumbnail_columns = 6 #int
gallery_fit = "contain" #str
generation_stop_event = threading.Event()

STOCHASTIC_SAMPLER_MARKERS = (" a", "ancestral", "sde")
STOCHASTIC_SCHEDULER_MARKERS = ("sde", "brownian", "turbo")
READ_ONLY_PRESET_NAMES = {"preview"}
READ_ONLY_PRESET_SUFFIXES = {"preview"}
READ_ONLY_PRESET_NOTICE = (
    "Preview is read-only because it displays Civitai Helper `modelname.preview.png` files. "
    "It can be selected for viewing, but its prompt/settings cannot be edited, deleted, duplicated, or generated by Thumbnailizer."
)
DELETE_PROTECTED_PRESET_NAMES = {"default", "preview"}
DELETE_PROTECTED_PRESET_SUFFIXES = {"", "preview"}
DELETE_PROTECTED_PRESET_NOTICE = (
    "Default and Preview are protected built-in sets. "
    "Default is the base `model.png` thumbnail set; Preview is the Civitai Helper `modelname.preview.png` view."
)
INPAINTING_FILENAME_MARKERS = ("inpaint", "inpainting")

# Load json data
def load_json_data():
    global data
    with open(sets_file_path, 'r') as file:
        data = json.load(file)


def save_json_data():
    with open(sets_file_path, 'w') as file:
        json.dump(data, file, indent=4)


def get_set_choices():
    return [item["displayName"] for item in data["sets"]]


def is_read_only_preset_item(set_item):
    set_item = set_item or {}
    display_name = str(set_item.get("displayName", "")).strip().lower()
    suffix = str(set_item.get("suffix", "")).strip().lower()
    return display_name in READ_ONLY_PRESET_NAMES or suffix in READ_ONLY_PRESET_SUFFIXES


def is_delete_protected_preset_item(set_item):
    set_item = set_item or {}
    display_name = str(set_item.get("displayName", "")).strip().lower()
    suffix = str(set_item.get("suffix", "")).strip().lower()
    return display_name in DELETE_PROTECTED_PRESET_NAMES or suffix in DELETE_PROTECTED_PRESET_SUFFIXES


def is_read_only_preset_name(set_name):
    return is_read_only_preset_item(get_set_data(set_name))


def get_read_only_preset_notice(set_name):
    return READ_ONLY_PRESET_NOTICE if is_read_only_preset_name(set_name) else ""


def get_generation_target_notice(set_name):
    set_item = get_set_data(set_name) or {}
    suffix = str(set_item.get("suffix", "")).strip()
    if is_read_only_preset_item(set_item):
        return "Preview is display-only. Thumbnailizer does not generate or modify Civitai Helper `modelname.preview.png` files."
    if suffix:
        return f"Generation target: writes sidecar thumbnail variants named `model.{suffix}.png` beside selected checkpoints."
    return (
        "Generation target: Default writes checkpoint default thumbnail files named `model.png` beside selected checkpoints. "
        "Existing `model.png` files are skipped unless regeneration is enabled."
    )


def is_inpainting_model_path(model_path):
    filename = Path(model_path).name.lower()
    return any(marker in filename for marker in INPAINTING_FILENAME_MARKERS)


def get_sampler_choices():
    try:
        choices = sd_samplers.visible_sampler_names()
        return choices or [x.name for x in sd_samplers.all_samplers]
    except Exception:
        return ["Euler a"]


def get_scheduler_choices():
    try:
        return [x.label for x in sd_schedulers.schedulers]
    except Exception:
        return ["Automatic"]


def normalize_prompt_text(*parts):
    return " ".join(str(part).strip() for part in parts if str(part).strip())


def apply_prompt_affixes(generation_set_data):
    prompt_prefix = generation_set_data.get("promptPrefix", "")
    prompt_suffix = generation_set_data.get("promptSuffix", "")
    negative_prefix = generation_set_data.get("negativePromptPrefix", "")
    negative_suffix = generation_set_data.get("negativePromptSuffix", "")

    generation_set_data["prompt"] = normalize_prompt_text(prompt_prefix, generation_set_data.get("prompt", ""), prompt_suffix)
    generation_set_data["negativePrompt"] = normalize_prompt_text(negative_prefix, generation_set_data.get("negativePrompt", ""), negative_suffix)
    return generation_set_data


def build_generation_set_data(base_set_data, use_override_settings=False):
    generation_set_data = apply_prompt_affixes(base_set_data.copy())

    if use_override_settings:
        override_settings = load_override_settings(override_settings_file)
        generation_set_data = apply_override_settings(generation_set_data, override_settings)

    return generation_set_data


def has_wildcard_syntax(prompt, negative_prompt):
    text = f"{prompt or ''}\n{negative_prompt or ''}"
    return "__" in text or ("{" in text and "}" in text and "|" in text)


def get_determinism_warnings(prompt, negative_prompt, sampler, scheduler, seed):
    warnings = []
    try:
        if int(seed) == -1:
            warnings.append("Seed is -1, so each run can vary.")
    except (TypeError, ValueError):
        warnings.append("Seed is not a valid integer.")

    sampler_text = str(sampler or "").lower()
    scheduler_text = str(scheduler or "").lower()
    if any(marker in sampler_text for marker in STOCHASTIC_SAMPLER_MARKERS):
        warnings.append("Sampler may be stochastic/noise-adding.")
    if any(marker in scheduler_text for marker in STOCHASTIC_SCHEDULER_MARKERS):
        warnings.append("Scheduler may affect repeatability.")
    if has_wildcard_syntax(prompt, negative_prompt):
        warnings.append("Wildcard syntax detected; resolved prompts may vary until explicit dynamic-prompts support lands.")

    if not warnings:
        return "Determinism check: no obvious stochastic settings detected."

    return "Determinism warnings:\n- " + "\n- ".join(warnings)


def get_preset_editor_values_from_set_item(set_item, set_name=""):
    set_item = set_item or {}
    return [
        set_item.get("displayName", set_name or ""),
        set_item.get("suffix", ""),
        set_item.get("prompt", ""),
        set_item.get("negativePrompt", ""),
        set_item.get("sampler", get_sampler_choices()[0]),
        set_item.get("scheduler", "Automatic"),
        int(set_item.get("steps", 25)),
        int(set_item.get("width", 420)),
        int(set_item.get("height", 640)),
        float(set_item.get("cfgScale", 6.0)),
        int(set_item.get("seed", -1)),
        set_item.get("promptPrefix", ""),
        set_item.get("promptSuffix", ""),
        set_item.get("negativePromptPrefix", ""),
        set_item.get("negativePromptSuffix", ""),
        get_determinism_warnings(
            normalize_prompt_text(set_item.get("promptPrefix", ""), set_item.get("prompt", ""), set_item.get("promptSuffix", "")),
            normalize_prompt_text(set_item.get("negativePromptPrefix", ""), set_item.get("negativePrompt", ""), set_item.get("negativePromptSuffix", "")),
            set_item.get("sampler", ""),
            set_item.get("scheduler", "Automatic"),
            set_item.get("seed", -1),
        ),
    ]


def get_preset_editor_values(set_name):
    return get_preset_editor_values_from_set_item(get_set_data(set_name), set_name)


def get_preset_action_updates(set_name):
    editable = not is_read_only_preset_name(set_name)
    deletable = not is_delete_protected_preset_item(get_set_data(set_name))
    return [
        gr.update(interactive=editable),
        gr.update(interactive=editable),
        gr.update(interactive=deletable),
        gr.update(interactive=editable),
        gr.update(interactive=editable),
    ]


def get_preset_editor_updates(set_name, preset_values=None):
    values = preset_values if preset_values is not None else get_preset_editor_values(set_name)
    interactive = not is_read_only_preset_name(set_name)
    editor_updates = [gr.update(value=value, interactive=interactive) for value in values[:-1]]
    return editor_updates + [
        values[-1],
        get_read_only_preset_notice(set_name),
        get_generation_target_notice(set_name),
    ] + get_preset_action_updates(set_name)


def preset_from_editor_values(display_name, suffix, prompt, negative_prompt, sampler, scheduler, steps, width, height, cfg_scale, seed, prompt_prefix, prompt_suffix, negative_prompt_prefix, negative_prompt_suffix):
    return {
        "displayName": str(display_name).strip() or "Unnamed",
        "suffix": str(suffix).strip(),
        "prompt": str(prompt or ""),
        "negativePrompt": str(negative_prompt or ""),
        "sampler": str(sampler or "Euler a"),
        "scheduler": str(scheduler or "Automatic"),
        "steps": int(steps),
        "width": int(width),
        "height": int(height),
        "cfgScale": float(cfg_scale),
        "seed": int(seed),
        "promptPrefix": str(prompt_prefix or ""),
        "promptSuffix": str(prompt_suffix or ""),
        "negativePromptPrefix": str(negative_prompt_prefix or ""),
        "negativePromptSuffix": str(negative_prompt_suffix or ""),
    }


def preset_editor_warnings(display_name, suffix, prompt, negative_prompt, sampler, scheduler, steps, width, height, cfg_scale, seed, prompt_prefix, prompt_suffix, negative_prompt_prefix, negative_prompt_suffix):
    return get_determinism_warnings(
        normalize_prompt_text(prompt_prefix, prompt, prompt_suffix),
        normalize_prompt_text(negative_prompt_prefix, negative_prompt, negative_prompt_suffix),
        sampler,
        scheduler,
        seed,
    )


def unique_name(base_name):
    existing = set(get_set_choices())
    if base_name not in existing:
        return base_name

    index = 2
    while f"{base_name} {index}" in existing:
        index += 1
    return f"{base_name} {index}"


def unique_suffix(base_suffix):
    existing = {item.get("suffix", "") for item in data["sets"]}
    candidate = base_suffix or "copy"
    if candidate not in existing:
        return candidate

    index = 2
    while f"{candidate}_{index}" in existing:
        index += 1
    return f"{candidate}_{index}"


ALL_CHECKPOINT_FOLDERS = "All folders"


def normalize_model_paths(model_paths):
    if model_paths is None:
        return []
    if isinstance(model_paths, str):
        return [model_paths]
    return [path for path in model_paths if path]


def get_checkpoint_folder(model_path):
    parent = Path(model_path).parent.as_posix()
    return parent if parent != "." else "(root)"


def get_checkpoint_folder_choices():
    folders = sorted({get_checkpoint_folder(path) for path in relevant_model_paths})
    return [ALL_CHECKPOINT_FOLDERS] + folders


def get_visible_model_paths(folder_filter=ALL_CHECKPOINT_FOLDERS):
    if not folder_filter or folder_filter == ALL_CHECKPOINT_FOLDERS:
        return list(relevant_model_paths)
    return [path for path in relevant_model_paths if get_checkpoint_folder(path) == folder_filter]


def get_thumbnail_path_for_model(model_path, suffix=""):
    model_path_obj = Path(model_path)
    thumb_file = f"{model_path_obj.stem}{suffix}.png"
    return Path(ckpt_dir) / model_path_obj.parent / thumb_file


def save_thumbnail_image_exact(image, output_path, geninfo=None):
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = output_path.with_name(f"{output_path.name}.tmp")
    images.save_image_with_geninfo(image, geninfo, str(temp_path), extension=".png")
    os.replace(temp_path, output_path)


def get_missing_model_paths(suffix="", model_paths=None):
    target_paths = relevant_model_paths if model_paths is None else model_paths
    return [path for path in target_paths if not get_thumbnail_path_for_model(path, suffix).exists()]


def get_suffix_for_set_name(set_name):
    set_item = get_set_data(set_name) or {}
    suffix = set_item.get("suffix", "")
    return f".{suffix}" if suffix else ""


def get_checkpoint_target_update(set_name, folder_filter=ALL_CHECKPOINT_FOLDERS, selected_paths=None):
    visible_paths = get_visible_model_paths(folder_filter)
    selected_paths = normalize_model_paths(selected_paths)
    if selected_paths:
        selected = [path for path in selected_paths if path in visible_paths]
    else:
        selected = get_missing_model_paths(get_suffix_for_set_name(set_name), visible_paths)

    return gr.update(choices=visible_paths, value=selected)

# Load settings.ini
def load_settings():
    global gallery_height, thumbnail_columns, gallery_fit
    config = configparser.ConfigParser()
    config.optionxform = str  # Keeps the case of options as is
    settings_path = os.path.join(script_dir, 'settings.ini')
    config.read(settings_path)
    # Update global variables with settings from file, if available
    gallery_height = int(config.get('Settings', 'gallery_height', fallback=gallery_height))
    thumbnail_columns = int(config.get('Settings', 'thumbnail_columns', fallback=thumbnail_columns))
    gallery_fit = str(config.get('Settings', 'gallery_fit', fallback=gallery_fit))

# Initialization function
def initialize(set_name="Default", model_blocklist_filename="blocklist_user"):
    global current_set_name, model_blocklist_file_path, blocklist, set_data, blocked_paths
    current_set_name = set_name
    model_blocklist_file_path = os.path.join(script_dir, f'{model_blocklist_filename}.json')
    load_settings()

    # Load the blocklist
    def load_model_blocklist():
        try:
            with open(model_blocklist_file_path, 'r') as f:
                return json.load(f)
        except FileNotFoundError:
            print("Error: Blocklist file not found.")
            return []
        except json.JSONDecodeError:
            print("Error: Blocklist not properly formatted.")
            return []
    blocklist = load_model_blocklist()

    # Load blocked paths
    blocked_paths_file = os.path.join(script_dir, 'blocked_paths_user.txt')
    if not os.path.exists(blocked_paths_file):
        with open(blocked_paths_file, 'w') as f:
            f.write("# List your folder paths to block here, one per line\n# True means this folder is hidden\n# False means it will be visible\n")
        blocked_paths = []
    else:
        with open(blocked_paths_file, 'r') as f:
            blocked_paths = []
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    parts = line.split(',')
                    if len(parts) == 2:
                        path, enabled = parts
                        blocked_paths.append((path, enabled.lower() == 'true'))
                    else:
                        blocked_paths.append((line, False))

    initialize_model_data()
    set_data = get_set_data(current_set_name)

# Initialize the model paths
def initialize_model_data():
    global all_model_names, all_model_paths, relevant_model_names, relevant_model_paths
    # Clear existing data
    all_model_names = []
    all_model_paths = []
    relevant_model_names = []
    relevant_model_paths = []

    # Set new data
    model_path = Path(ckpt_dir)
    model_files = glob.glob(model_path.joinpath("**/*").as_posix(), recursive=True)

    for m in model_files:
        if Path(m).suffix in {".ckpt", ".safetensors"}:
            rel_path = os.path.relpath(m, model_path.as_posix())
            all_model_names.append(Path(rel_path).name)
            all_model_paths.append(rel_path)

            # Normalize the path for comparison
            normalized_path = Path(rel_path).as_posix()

            # Check if the model is in a blocked folder path
            is_blocked = False
            for path, enabled in blocked_paths:
                if normalized_path.startswith(Path(path).as_posix()):
                    is_blocked = enabled
                if normalized_path == Path(path).as_posix() and not enabled:
                    is_blocked = False
                    break

            if is_inpainting_model_path(rel_path):
                print(f"Thumbnailizer: Excluding inpainting checkpoint by filename: {rel_path}")
            elif rel_path not in blocklist and not is_blocked:
                relevant_model_names.append(Path(rel_path).name)
                relevant_model_paths.append(rel_path)


# Function to get the data of a specific set
def get_set_data(set_name):
    with open(sets_file_path, 'r') as file:
        data = json.load(file)
        for set_item in data["sets"]:
            if set_item["displayName"] == set_name:
                return set_item
    return None  # Return None if set not found

# Run initialization
initialize()
load_json_data()

# Function to get model thumbnail paths
def get_relevant_thumbnails(suffix="", model_paths=None):
    global ckpt_dir
    thumbnails = []
    missing_thumbnail_path = Path(script_dir) / "card-no-preview.png"
    target_model_paths = relevant_model_paths if model_paths is None else model_paths

    for model_path in target_model_paths:
        model_path_obj = Path(model_path)

        # Correctly split the model name, preserving all but the last extension
        full_model_name = model_path_obj.name

        # Check for thumbnail with set-specific suffix
        thumbnail_path_with_suffix = get_thumbnail_path_for_model(model_path, suffix)

        # Check for thumbnail without set-specific suffix (default)
        thumbnail_path_without_suffix = get_thumbnail_path_for_model(model_path, "")

        # Check for thumbnails in this order: with suffix, without suffix, default
        if suffix and thumbnail_path_with_suffix.exists():
            thumbnails.append((str(thumbnail_path_with_suffix), full_model_name))
        elif suffix and not thumbnail_path_with_suffix.exists():
            thumbnails.append((str(missing_thumbnail_path), full_model_name))
        elif not suffix and thumbnail_path_without_suffix.exists():
            thumbnails.append((str(thumbnail_path_without_suffix), full_model_name))
        else:
            thumbnails.append((str(missing_thumbnail_path), full_model_name))

    return thumbnails


# Start thumbnail generation
def generate_thumbnails(set_name, set_data, suffix, model_paths, regenerate_existing=False, use_override_settings=False):
    model_paths = normalize_model_paths(model_paths)
    if not model_paths:
        return "No checkpoint targets selected."

    generation_stop_event.clear()
    shared.state.begin(job="thumbnailizer")
    completed = 0
    skipped = 0
    failed = 0

    try:
        print(f"--------------------------------------------------------")
        print(f"Thumbnailizer generation initializing for preset: {set_name}")
        print(f"Selected checkpoint targets: {len(model_paths)}")
        print(f"Current suffix: {suffix}")

        generation_set_data = build_generation_set_data(set_data, use_override_settings)

        if use_override_settings:
            override_settings = load_override_settings(override_settings_file)
            print("Using settings override:")
            for key, value in override_settings.items():
                if value:
                    print(f"  {key}: {value}")
        else:
            print("Not using settings override")

        print("Resolved Thumbnailizer generation parameters:")
        for key in ["prompt", "negativePrompt", "sampler", "scheduler", "steps", "width", "height", "cfgScale", "seed"]:
            print(f"  {key}: {generation_set_data.get(key)}")

        for i, model_path in enumerate(model_paths):
            if generation_stop_event.is_set() or shared.state.interrupted or shared.state.stopping_generation:
                print("Thumbnailizer generation stopped before next checkpoint.")
                break

            model_name = Path(model_path).name
            full_model_path = os.path.join(ckpt_dir, model_path)
            print(f"Thumbnailizer target {i + 1}/{len(model_paths)}: {model_path}")

            try:
                result = generate_thumbnail_for_model(generation_set_data, model_name, suffix, model_path, full_model_path, use_override_settings, regenerate_existing)
                if result == "generated":
                    completed += 1
                elif result == "skipped":
                    skipped += 1
                elif result == "interrupted":
                    print("Thumbnailizer generation interrupted during current checkpoint.")
                    break
                else:
                    failed += 1
                print(f"Thumbnailizer progress: generated={completed}, skipped_existing={skipped}, failed={failed}, total_targets={len(model_paths)}")
            except Exception as e:
                failed += 1
                print(f"Error generating thumbnail for {model_path}: {e}")

        stopped = generation_stop_event.is_set() or shared.state.interrupted or shared.state.stopping_generation
        status_prefix = "Stopped" if stopped else "Finished"
        message = (
            f"{status_prefix} preset '{set_name}': generated {completed}, "
            f"skipped existing {skipped}, failed {failed}, targets {len(model_paths)}."
        )
        print(f"\nThumbnailizer - {message}")
        return message
    finally:
        shared.state.end()

# Generate thumbnails for specific model (called from generate_thumbnails)
def generate_thumbnail_for_model(generation_set_data, model_name, suffix, model_path, full_model_path, use_override_settings, regenerate_existing=False):

    # Initialize processed to None
    processed = None
    try:
        if use_override_settings:
            print(f"Thumbnailizer: Using override settings for model: {model_name}")
        else:
            print(f"Thumbnailizer: Not using override settings for model: {model_name}")

        print(f"Thumbnailizer: Generation metadata for {model_path}:")
        for key, value in generation_set_data.items():
            print(f"  {key}: {value}")

        # Set up processing parameters
        p = processing.StableDiffusionProcessingTxt2Img(
            sd_model=shared.sd_model,
            prompt=generation_set_data.get("prompt", "Default Prompt"),
            negative_prompt=generation_set_data.get("negativePrompt", ""),
            steps=int(generation_set_data.get("steps", 25)),
            cfg_scale=float(generation_set_data.get("cfgScale", 6.0)),
            sampler_name=generation_set_data.get("sampler", "Default Sampler"),
            width=int(generation_set_data.get("width", 420)),
            height=int(generation_set_data.get("height", 640)),
            seed=int(generation_set_data.get("seed", -1)),
            override_settings={"sd_model_checkpoint": model_path}
        )
        scheduler_name = generation_set_data.get("scheduler", None)
        if scheduler_name:
            p.scheduler = scheduler_name

        model_name_without_ext = model_name.rsplit('.', 1)[0]
        model_directory = Path(ckpt_dir) / Path(model_path).parent
        output_filename = f"{model_name_without_ext}{suffix}"
        output_path = model_directory / f"{output_filename}.png"

        # Check if thumbnail already exists and skip if not overwriting
        if not regenerate_existing and output_path.exists():
            print(f"Thumbnail already exists for {model_path}, skipping...")
            return "skipped"

        p.do_not_save_samples = True
        # disable saving of grid
        p.do_not_save_grid = True
        # disable saving image to subdirectories
        p.override_settings['save_to_dirs'] = False
        # set image output directory
        p.outpath_samples = str(model_directory)
        # set the image filename
        p.override_settings['samples_filename_pattern'] = output_filename
        print(f"Generating thumbnail for model: {model_name} at path: {full_model_path} with output: {output_path}")
        print(f"Resolved processing steps before process_images: {p.steps}")

        # Process the image
        with closing(p):
            if processed is None:
                try:
                    processed = processing.process_images(p)
                except AttributeError as ae:
                    if "'NoneType' object has no attribute 'options'" in str(ae):
                        print(f"Warning: Sampler configuration issue for {model_name}. Trying with default sampler.")
                        p.sampler_name = "Euler a"  # Use a default sampler
                        processed = processing.process_images(p)
                    else:
                        raise
        if shared.state.interrupted or shared.state.stopping_generation:
            return "interrupted"
        # Ensure that images were generated
        if not processed or not processed.images:
            raise ValueError("No images were generated.")
        geninfo = processed.infotexts[0] if getattr(processed, "infotexts", None) else None
        save_thumbnail_image_exact(processed.images[0], output_path, geninfo)
        if not output_path.exists():
            raise FileNotFoundError(f"Expected thumbnail was not written: {output_path}")
        print(f"\n\nThumbnail generated and saved as {output_path}")
        return "generated"
    except Exception as e:
        print(f"Error in generating thumbnail for {model_name}: {e}")
        traceback.print_exc()
        return "failed"

# Load model paths and blocklist for the dropdown
def update_gallery(set_name, folder_filter=ALL_CHECKPOINT_FOLDERS):
    global current_suffix, data
    suffix = ""
    for item in data["sets"]:
        if item["displayName"] == set_name:
            suffix = item['suffix']
            if suffix:
                suffix = '.' + suffix  # Only add a period if the suffix is not empty
            break
    print(f"Thumbnailizer: Switched to set: {set_name} ({suffix})")
    current_suffix = suffix
    thumbnails = get_relevant_thumbnails(suffix, get_visible_model_paths(folder_filter))

    return [(path, name) for path, name in thumbnails]

# Functionality to generate thumbnails for all sets
def generate_thumbnails_for_all_sets(model_paths, regenerate_existing=False, use_override_settings=False):
    global data, current_set_name, set_data

    model_paths = normalize_model_paths(model_paths)
    if not model_paths:
        return "No checkpoint targets selected."

    generation_sets = [set_item for set_item in data["sets"] if not is_read_only_preset_item(set_item)]
    read_only_preset_count = len(data["sets"]) - len(generation_sets)
    if not generation_sets:
        return "No editable generation presets are available. Read-only preview presets are display-only."

    generation_stop_event.clear()
    shared.state.begin(job="thumbnailizer-all-presets")
    original_set_name = current_set_name
    original_set_data = set_data
    completed = 0
    skipped = 0
    failed = 0
    total_targets = len(model_paths) * len(generation_sets)

    try:
        for model_path in model_paths:
            model_name = Path(model_path).name

            for set_item in generation_sets:
                if generation_stop_event.is_set() or shared.state.interrupted or shared.state.stopping_generation:
                    print("Thumbnailizer all-preset generation stopped before next target.")
                    break

                set_name = set_item["displayName"]
                suffix = f".{set_item['suffix']}" if set_item['suffix'] else ''
                current_set_name = set_name
                set_data = set_item
                generation_set_data = build_generation_set_data(set_item, use_override_settings)

                print(f"Generating thumbnail for preset: {set_name}; checkpoint: {model_path}; suffix: {suffix}")
                print("Resolved Thumbnailizer generation parameters:")
                for key in ["sampler", "scheduler", "steps", "width", "height", "cfgScale", "seed"]:
                    print(f"  {key}: {generation_set_data.get(key)}")

                result = generate_thumbnail_for_model(
                    generation_set_data,
                    model_name,
                    suffix,
                    model_path,
                    os.path.join(ckpt_dir, model_path),
                    use_override_settings,
                    regenerate_existing,
                )
                if result == "generated":
                    completed += 1
                elif result == "skipped":
                    skipped += 1
                elif result == "interrupted":
                    print("Thumbnailizer all-preset generation interrupted during current target.")
                    break
                else:
                    failed += 1

            if generation_stop_event.is_set() or shared.state.interrupted or shared.state.stopping_generation:
                break

        stopped = generation_stop_event.is_set() or shared.state.interrupted or shared.state.stopping_generation
        status_prefix = "Stopped" if stopped else "Finished"
        message = (
            f"{status_prefix} all presets: generated {completed}, "
            f"skipped existing {skipped}, failed {failed}, targets {total_targets}, "
            f"read-only presets skipped {read_only_preset_count}."
        )
        print(f"Thumbnailizer - {message}")
        return message
    finally:
        current_set_name = original_set_name
        set_data = original_set_data
        shared.state.end()

    
# Thumbnailizer UI
def on_ui_tabs():
    global current_suffix, gallery, blocked_paths, current_set_name, set_data
    current_suffix = ''    # Initialize with empty string

    # Load choices from JSON
    load_json_data()
    set_choices = get_set_choices()
    initial_set_name = current_set_name if current_set_name in set_choices else set_choices[0]
    initial_preset_read_only = is_read_only_preset_name(initial_set_name)
    initial_preset_delete_protected = is_delete_protected_preset_item(get_set_data(initial_set_name))
    
    # Function to save model blocklist to a file
    def save_model_blocklist(selected_models):
        with open(model_blocklist_file_path, 'w') as f:
            json.dump(selected_models, f)
        print("Thumbnailizer: Model blocklist saved to:", model_blocklist_file_path, "")
        return "Model blocklist saved!"

    with gr.Blocks(analytics_enabled=False) as ui_component:
        # Apply CSS style
        gr.Markdown(f"<link rel='stylesheet' type='text/css' href='{script_dir}/style.css'>")

        ######################## SET SETTINGS SECTION ########################
        with GradioBox(elem_classes="ch_box"):
            with gr.Row():
                with gr.Column(scale=1, min_width=110):
                    gr.Markdown("**Set List**")
                with gr.Column(scale=5, min_width=240):
                    set_dropdown = gr.Dropdown(choices=set_choices, value=initial_set_name, show_label=False)
            with gr.Accordion("Generation Preset Editor", open=False):
                gr.Markdown(
                    "Preset fields are saved as static values in `sets_user.json`. "
                    "Generation uses `Prompt Prefix + Prompt + Prompt Suffix` and "
                    "`Negative Prompt Prefix + Negative Prompt + Negative Prompt Suffix`."
                )
                gr.Markdown(
                    "Advanced prompt affix fields are optional static concatenation helpers. "
                    "They are hidden by default but still saved in `sets_user.json` and applied during generation when non-empty."
                )
                gr.Markdown(
                    "Preset edits are saved to `{}`. `{}` remains the default seed file only.".format(
                        user_sets_file_path,
                        os.path.join(script_dir, 'sets_template.json')
                    )
                )
                read_only_preset_message = gr.Markdown(get_read_only_preset_notice(initial_set_name))
                generation_target_message = gr.Markdown(get_generation_target_notice(initial_set_name))
                with gr.Row():
                    preset_display_name = gr.Textbox(
                        label="Display Name",
                        value=get_preset_editor_values(initial_set_name)[0],
                        info="Human-readable preset name shown in the Set List. This does not control output filenames.",
                        interactive=not initial_preset_read_only,
                    )
                    preset_suffix = gr.Textbox(
                        label="Thumbnail Filename Suffix",
                        value=get_preset_editor_values(initial_set_name)[1],
                        info="File variant key appended to each checkpoint thumbnail, e.g. model.environment.png. Leave empty only for the default model.png thumbnail.",
                        interactive=not initial_preset_read_only,
                    )
                with gr.Row():
                    preset_prompt = gr.Textbox(
                        label="Prompt",
                        lines=4,
                        value=get_preset_editor_values(initial_set_name)[2],
                        info="Main positive prompt for this thumbnail set.",
                        interactive=not initial_preset_read_only,
                    )
                    preset_negative_prompt = gr.Textbox(
                        label="Negative Prompt",
                        lines=4,
                        value=get_preset_editor_values(initial_set_name)[3],
                        info="Main negative prompt for this thumbnail set.",
                        interactive=not initial_preset_read_only,
                    )
                with gr.Row():
                    preset_sampler = gr.Dropdown(choices=get_sampler_choices(), label="Sampler", value=get_preset_editor_values(initial_set_name)[4], allow_custom_value=True, interactive=not initial_preset_read_only)
                    preset_scheduler = gr.Dropdown(choices=get_scheduler_choices(), label="Scheduler", value=get_preset_editor_values(initial_set_name)[5], allow_custom_value=True, info="Forge Neo scheduler to pass to generation when available. Automatic lets the backend choose.", interactive=not initial_preset_read_only)
                with gr.Row():
                    preset_steps = gr.Number(label="Steps", value=get_preset_editor_values(initial_set_name)[6], precision=0, interactive=not initial_preset_read_only)
                    preset_width = gr.Number(label="Width", value=get_preset_editor_values(initial_set_name)[7], precision=0, interactive=not initial_preset_read_only)
                    preset_height = gr.Number(label="Height", value=get_preset_editor_values(initial_set_name)[8], precision=0, interactive=not initial_preset_read_only)
                    preset_cfg_scale = gr.Number(label="CFG Scale", value=get_preset_editor_values(initial_set_name)[9], interactive=not initial_preset_read_only)
                    preset_seed = gr.Number(label="Seed", value=get_preset_editor_values(initial_set_name)[10], precision=0, interactive=not initial_preset_read_only)
                with gr.Accordion("Advanced prompt affix fields", open=False):
                    gr.Markdown(
                        "These fields are static prompt wrappers, not dynamic variables. "
                        "They stay in the preset JSON even when hidden."
                    )
                    with gr.Row():
                        preset_prompt_prefix = gr.Textbox(
                            label="Prompt Prefix",
                            value=get_preset_editor_values(initial_set_name)[11],
                            info="Static text prepended before Prompt at generation time. Useful for shared model triggers or quality tags.",
                            interactive=not initial_preset_read_only,
                        )
                        preset_prompt_suffix = gr.Textbox(
                            label="Prompt Suffix",
                            value=get_preset_editor_values(initial_set_name)[12],
                            info="Static text appended after Prompt at generation time. Useful for reusable style, camera, or quality endings.",
                            interactive=not initial_preset_read_only,
                        )
                    with gr.Row():
                        preset_negative_prompt_prefix = gr.Textbox(
                            label="Negative Prompt Prefix",
                            value=get_preset_editor_values(initial_set_name)[13],
                            info="Static text prepended before Negative Prompt. Useful for broad default negatives.",
                            interactive=not initial_preset_read_only,
                        )
                        preset_negative_prompt_suffix = gr.Textbox(
                            label="Negative Prompt Suffix",
                            value=get_preset_editor_values(initial_set_name)[14],
                            info="Static text appended after Negative Prompt. Useful for reusable cleanup or model-specific negatives.",
                            interactive=not initial_preset_read_only,
                        )
                with gr.Row():
                    determinism_warning = gr.Markdown(get_preset_editor_values(initial_set_name)[15])
                with gr.Row():
                    save_preset_button = gr.Button("Save Preset", interactive=not initial_preset_read_only)
                    duplicate_preset_button = gr.Button("Duplicate Preset", interactive=not initial_preset_read_only)
                    delete_preset_button = gr.Button("Delete Preset", interactive=not initial_preset_delete_protected)
                    reload_presets_button = gr.Button("Reload Presets")
                with gr.Row():
                    folder_filter_dropdown = gr.Dropdown(
                        label="Checkpoint Folder",
                        choices=get_checkpoint_folder_choices(),
                        value=ALL_CHECKPOINT_FOLDERS,
                    )
                with gr.Row():
                    checkpoint_targets = gr.Dropdown(
                        label="Checkpoint Targets (relative paths)",
                        choices=get_visible_model_paths(ALL_CHECKPOINT_FOLDERS),
                        value=get_missing_model_paths(get_suffix_for_set_name(initial_set_name), get_visible_model_paths(ALL_CHECKPOINT_FOLDERS)),
                        multiselect=True,
                    )
                with gr.Row():
                    select_missing_button = gr.Button("Select Missing")
                    select_visible_button = gr.Button("Select Visible")
                    clear_targets_button = gr.Button("Clear")
                    refresh_gallery_button = gr.Button("Refresh Gallery")
                with gr.Row():
                    regenerate_existing_checkbox = gr.Checkbox(label="Regenerate thumbnails that already exist", value=False)
                    use_override_settings_checkbox = gr.Checkbox(label="Use Override Settings (edit override_settings_user.txt)", value=False)
                    stop_generation_button = gr.Button("Stop Thumbnailizer Generation")
                with gr.Row():
                    generate_button = gr.Button("Generate Selected Preset for Selected Checkpoints", interactive=not initial_preset_read_only)
                with gr.Accordion("All preset batch generation", open=False):
                    gr.Markdown(
                        "Batch action: generates every saved preset for the selected checkpoint targets above."
                    )
                    with gr.Row():
                        generate_all_button = gr.Button("Generate All Presets for Selected Checkpoints", interactive=not initial_preset_read_only)
                with gr.Row():
                    generating_message = gr.Markdown()
                with gr.Row():
                    preset_message = gr.Markdown()

            preset_editor_inputs = [
                preset_display_name,
                preset_suffix,
                preset_prompt,
                preset_negative_prompt,
                preset_sampler,
                preset_scheduler,
                preset_steps,
                preset_width,
                preset_height,
                preset_cfg_scale,
                preset_seed,
                preset_prompt_prefix,
                preset_prompt_suffix,
                preset_negative_prompt_prefix,
                preset_negative_prompt_suffix,
            ]
            preset_editor_outputs = preset_editor_inputs + [
                determinism_warning,
                read_only_preset_message,
                generation_target_message,
                save_preset_button,
                duplicate_preset_button,
                delete_preset_button,
                generate_button,
                generate_all_button,
            ]

        ######################## GALLERY SECTION ########################
        with GradioBox(elem_classes="ch_box"):
            # Gallery
            with gr.Row():
                gallery = gr.Gallery(value=get_relevant_thumbnails(current_suffix), columns=thumbnail_columns, height=gallery_height, object_fit=gallery_fit)

        def select_missing_targets(set_name, folder_filter):
            return get_checkpoint_target_update(set_name, folder_filter)

        def select_visible_targets(folder_filter):
            visible_paths = get_visible_model_paths(folder_filter)
            return gr.update(choices=visible_paths, value=visible_paths)

        def clear_checkpoint_targets(folder_filter):
            return gr.update(choices=get_visible_model_paths(folder_filter), value=[])

        def refresh_generation_gallery(set_name, folder_filter, selected_model_paths):
            return update_gallery(set_name, folder_filter), get_checkpoint_target_update(set_name, folder_filter, selected_model_paths)

        def stop_thumbnailizer_generation():
            generation_stop_event.set()
            shared.state.interrupt()
            return "Stop requested. Thumbnailizer will stop the current image and will not continue to the next checkpoint target."

        def display_generating_message(set_name, display_name, suffix, prompt, negative_prompt, sampler, scheduler, steps, width, height, cfg_scale, seed, prompt_prefix, prompt_suffix, negative_prompt_prefix, negative_prompt_suffix, selected_model_paths, folder_filter, regenerate_existing, use_override_settings):
            current_set_data = preset_from_editor_values(display_name, suffix, prompt, negative_prompt, sampler, scheduler, steps, width, height, cfg_scale, seed, prompt_prefix, prompt_suffix, negative_prompt_prefix, negative_prompt_suffix)
            if is_read_only_preset_name(set_name) or is_read_only_preset_item(current_set_data):
                return READ_ONLY_PRESET_NOTICE, update_gallery(set_name, folder_filter), get_checkpoint_target_update(set_name, folder_filter)
            current_suffix = f".{current_set_data['suffix']}" if current_set_data['suffix'] else ''
            message = generate_thumbnails(current_set_data["displayName"], current_set_data, current_suffix, selected_model_paths, regenerate_existing, use_override_settings)
            return message, update_gallery(set_name, folder_filter), get_checkpoint_target_update(set_name, folder_filter)

        def display_generating_all_message(set_name, selected_model_paths, folder_filter, regenerate_existing, use_override_settings):
            message = generate_thumbnails_for_all_sets(selected_model_paths, regenerate_existing, use_override_settings)
            return message, update_gallery(set_name, folder_filter), get_checkpoint_target_update(set_name, folder_filter)

        folder_filter_dropdown.change(
            fn=refresh_generation_gallery,
            inputs=[set_dropdown, folder_filter_dropdown, checkpoint_targets],
            outputs=[gallery, checkpoint_targets]
        )

        select_missing_button.click(
            fn=select_missing_targets,
            inputs=[set_dropdown, folder_filter_dropdown],
            outputs=[checkpoint_targets]
        )

        select_visible_button.click(
            fn=select_visible_targets,
            inputs=[folder_filter_dropdown],
            outputs=[checkpoint_targets]
        )

        clear_targets_button.click(
            fn=clear_checkpoint_targets,
            inputs=[folder_filter_dropdown],
            outputs=[checkpoint_targets]
        )

        refresh_gallery_button.click(
            fn=refresh_generation_gallery,
            inputs=[set_dropdown, folder_filter_dropdown, checkpoint_targets],
            outputs=[gallery, checkpoint_targets]
        )

        stop_generation_button.click(
            fn=stop_thumbnailizer_generation,
            outputs=[generating_message]
        )

        generate_button.click(
            fn=display_generating_message,
            inputs=[set_dropdown] + preset_editor_inputs + [checkpoint_targets, folder_filter_dropdown, regenerate_existing_checkbox, use_override_settings_checkbox],
            outputs=[generating_message, gallery, checkpoint_targets]
        )

        generate_all_button.click(
            fn=display_generating_all_message,
            inputs=[set_dropdown, checkpoint_targets, folder_filter_dropdown, regenerate_existing_checkbox, use_override_settings_checkbox],
            outputs=[generating_message, gallery, checkpoint_targets]
        )

        ######################## BLOCKLIST SECTION ########################
        with GradioBox(elem_classes="ch_box"):
            # Load the current blocklist

            # Keep stored model paths as-is; relpath() fails across Windows drives.
            model_choices = [p for p in all_model_paths]

            # Blocklist Dropdown
            with gr.Row():
                model_list_dropdown = gr.Dropdown(label="Model Blocklist", choices=model_choices, multiselect=True, value=blocklist)
            with gr.Row():
                save_selection_button = gr.Button("Save Model Blocklist")
            with gr.Row():
                blocklist_message = gr.Markdown()

            # Function to save model blocklist and update message
            def save_model_blocklist_and_update_message(selected_models):
                global blocklist, data
                blocklist = selected_models
                with open(model_blocklist_file_path, 'w') as f:
                    json.dump(selected_models, f)
                print("Thumbnailizer: Model blocklist saved to:", model_blocklist_file_path)
                
                # Re-initialize with the new blocklist
                initialize(current_set_name)
                
                # Reload JSON data
                load_json_data()
                
                message = f"Blocklist updated: {model_blocklist_file_path}"
                return (
                    message,
                    update_gallery(current_set_name, ALL_CHECKPOINT_FOLDERS),
                    gr.update(choices=get_checkpoint_folder_choices(), value=ALL_CHECKPOINT_FOLDERS),
                    get_checkpoint_target_update(current_set_name, ALL_CHECKPOINT_FOLDERS),
                )

            # Update the save blocklist button click event
            save_selection_button.click(
                fn=save_model_blocklist_and_update_message,
                inputs=[model_list_dropdown],
                outputs=[blocklist_message, gallery, folder_filter_dropdown, checkpoint_targets]
            )
                    
        ######################## BLOCKED PATHS SECTION ########################
        with GradioBox(elem_classes="ch_box"):
            gr.Markdown("## Blocked Paths")
            gr.Markdown(f"To edit the available blocked paths, open this file with a text editor: `{os.path.join(script_dir, 'blocked_paths_user.txt')}`")
            blocked_paths_checkboxes = gr.CheckboxGroup(
                choices=[path for path, _ in blocked_paths],
                value=[path for path, enabled in blocked_paths if enabled], label="Select which paths to block and ignore."
            )
            with gr.Row():
                update_blocked_paths_button = gr.Button("Update Blocked Paths")
            with gr.Row():
                blocked_paths_message = gr.Markdown()

        # Function to update blocked paths
        def update_blocked_paths(checkbox_values):
            global blocked_paths
            updated_paths = [(path, path in checkbox_values) for path, _ in blocked_paths]
            with open(os.path.join(script_dir, 'blocked_paths_user.txt'), 'w') as f:
                f.write("# List your folder paths to block here, one per line\n# True means this folder is hidden\n# False means it will be visible\n")
                for path, enabled in updated_paths:
                    f.write(f"{path},{enabled}\n")
            blocked_paths = updated_paths
            
            # Re-initialize model data after updating blocked paths
            initialize_model_data()
            
            return (
                "Blocked paths updated successfully!",
                update_gallery(current_set_name, ALL_CHECKPOINT_FOLDERS),
                gr.update(choices=get_checkpoint_folder_choices(), value=ALL_CHECKPOINT_FOLDERS),
                get_checkpoint_target_update(current_set_name, ALL_CHECKPOINT_FOLDERS),
            )

        # Update blocked paths button
        update_blocked_paths_button.click(
            fn=update_blocked_paths,
            inputs=blocked_paths_checkboxes,
            outputs=[blocked_paths_message, gallery, folder_filter_dropdown, checkpoint_targets]
        )
        
        ######################## MISC ########################
        def refresh_preset_view(selected_set_name, message, folder_filter=ALL_CHECKPOINT_FOLDERS, preset_values=None):
            choices = get_set_choices()
            if not choices:
                return [gr.update(choices=[], value=None), "No presets are available.", [], gr.update(choices=[], value=[])] + get_preset_editor_updates("")
            selected = selected_set_name if selected_set_name in choices else choices[0]
            gallery_data = update_gallery(selected, folder_filter)
            target_update = get_checkpoint_target_update(selected, folder_filter)
            return [gr.update(choices=choices, value=selected), message, gallery_data, target_update] + get_preset_editor_updates(selected, preset_values)

        def save_selected_preset(selected_set_name, display_name, suffix, prompt, negative_prompt, sampler, scheduler, steps, width, height, cfg_scale, seed, prompt_prefix, prompt_suffix, negative_prompt_prefix, negative_prompt_suffix, folder_filter):
            global current_set_name, set_data, current_suffix, data
            new_preset = preset_from_editor_values(display_name, suffix, prompt, negative_prompt, sampler, scheduler, steps, width, height, cfg_scale, seed, prompt_prefix, prompt_suffix, negative_prompt_prefix, negative_prompt_suffix)
            selected_index = next((index for index, item in enumerate(data["sets"]) if item["displayName"] == selected_set_name), None)

            if selected_index is None:
                return refresh_preset_view(selected_set_name, f"Preset not found: {selected_set_name}", folder_filter)
            if is_read_only_preset_item(data["sets"][selected_index]):
                return refresh_preset_view(selected_set_name, READ_ONLY_PRESET_NOTICE, folder_filter)
            if is_read_only_preset_item(new_preset):
                return refresh_preset_view(selected_set_name, "The Preview name/suffix is reserved for Civitai Helper thumbnails and cannot be used for editable presets.", folder_filter)

            existing_names = {item["displayName"] for index, item in enumerate(data["sets"]) if index != selected_index}
            if new_preset["displayName"] in existing_names:
                return refresh_preset_view(selected_set_name, f"Preset name already exists: {new_preset['displayName']}", folder_filter)

            data["sets"][selected_index] = new_preset
            save_json_data()
            current_set_name = new_preset["displayName"]
            set_data = new_preset
            current_suffix = f".{new_preset['suffix']}" if new_preset["suffix"] else ''
            return refresh_preset_view(
                current_set_name,
                f"Saved preset to {user_sets_file_path}",
                folder_filter,
                get_preset_editor_values_from_set_item(new_preset, current_set_name),
            )

        def duplicate_selected_preset(display_name, suffix, prompt, negative_prompt, sampler, scheduler, steps, width, height, cfg_scale, seed, prompt_prefix, prompt_suffix, negative_prompt_prefix, negative_prompt_suffix, folder_filter):
            global current_set_name, set_data, current_suffix, data
            copied_preset = preset_from_editor_values(display_name, suffix, prompt, negative_prompt, sampler, scheduler, steps, width, height, cfg_scale, seed, prompt_prefix, prompt_suffix, negative_prompt_prefix, negative_prompt_suffix)
            if is_read_only_preset_item(copied_preset):
                return refresh_preset_view(current_set_name, "Read-only Preview presets cannot be duplicated.", folder_filter)
            copied_preset["displayName"] = unique_name(f"{copied_preset['displayName']} Copy")
            copied_preset["suffix"] = unique_suffix(f"{copied_preset['suffix']}_copy" if copied_preset["suffix"] else "copy")
            data["sets"].append(copied_preset)
            save_json_data()
            current_set_name = copied_preset["displayName"]
            set_data = copied_preset
            current_suffix = f".{copied_preset['suffix']}" if copied_preset["suffix"] else ''
            return refresh_preset_view(
                current_set_name,
                f"Duplicated preset to {user_sets_file_path}",
                folder_filter,
                get_preset_editor_values_from_set_item(copied_preset, current_set_name),
            )

        def delete_selected_preset(selected_set_name, folder_filter):
            global current_set_name, set_data, current_suffix, data
            if len(data["sets"]) <= 1:
                return refresh_preset_view(selected_set_name, "Cannot delete the last remaining preset.", folder_filter)

            selected_index = next((index for index, item in enumerate(data["sets"]) if item["displayName"] == selected_set_name), None)
            if selected_index is None:
                return refresh_preset_view(selected_set_name, f"Preset not found: {selected_set_name}", folder_filter)
            if is_delete_protected_preset_item(data["sets"][selected_index]):
                return refresh_preset_view(selected_set_name, DELETE_PROTECTED_PRESET_NOTICE, folder_filter)

            deleted_preset = data["sets"].pop(selected_index)
            next_index = min(selected_index, len(data["sets"]) - 1)
            next_preset = data["sets"][next_index]
            save_json_data()
            current_set_name = next_preset["displayName"]
            set_data = next_preset
            current_suffix = f".{next_preset['suffix']}" if next_preset["suffix"] else ''
            return refresh_preset_view(
                current_set_name,
                f"Deleted preset '{deleted_preset['displayName']}' from {user_sets_file_path}",
                folder_filter,
                get_preset_editor_values_from_set_item(next_preset, current_set_name),
            )

        def reload_presets(selected_set_name, folder_filter):
            global data
            load_json_data()
            return refresh_preset_view(selected_set_name, f"Reloaded presets from {user_sets_file_path}", folder_filter)

        # Handle set changes
        def on_set_change(set_name, folder_filter):
            global current_set_name, set_data, current_suffix
            choices = get_set_choices()
            if set_name not in choices:
                selected = choices[0] if choices else ""
                return refresh_preset_view(selected, f"Preset no longer exists: {set_name}", folder_filter)

            current_set_name = set_name
            set_data = get_set_data(current_set_name)
            if set_data is None:
                selected = choices[0] if choices else ""
                return refresh_preset_view(selected, f"Preset no longer exists: {set_name}", folder_filter)

            # Update current_suffix based on the new set
            current_suffix = f".{set_data['suffix']}" if set_data['suffix'] else ''
            # Re-initialize
            initialize(current_set_name)

            # Update the gallery
            gallery_data = update_gallery(set_name, folder_filter)
            target_update = get_checkpoint_target_update(set_name, folder_filter)
            return [gr.update(choices=choices, value=set_name), "", gallery_data, target_update] + get_preset_editor_updates(set_name)

        for editor_input in preset_editor_inputs:
            editor_input.change(
                fn=preset_editor_warnings,
                inputs=preset_editor_inputs,
                outputs=[determinism_warning]
            )

        save_preset_button.click(
            fn=save_selected_preset,
            inputs=[set_dropdown] + preset_editor_inputs + [folder_filter_dropdown],
            outputs=[set_dropdown, preset_message, gallery, checkpoint_targets] + preset_editor_outputs
        )

        duplicate_preset_button.click(
            fn=duplicate_selected_preset,
            inputs=preset_editor_inputs + [folder_filter_dropdown],
            outputs=[set_dropdown, preset_message, gallery, checkpoint_targets] + preset_editor_outputs
        )

        delete_preset_button.click(
            fn=delete_selected_preset,
            inputs=[set_dropdown, folder_filter_dropdown],
            outputs=[set_dropdown, preset_message, gallery, checkpoint_targets] + preset_editor_outputs
        )

        reload_presets_button.click(
            fn=reload_presets,
            inputs=[set_dropdown, folder_filter_dropdown],
            outputs=[set_dropdown, preset_message, gallery, checkpoint_targets] + preset_editor_outputs
        )

        # Event handling for the Set List dropdown change
        set_dropdown.change(
            fn=on_set_change,
            inputs=[set_dropdown, folder_filter_dropdown],
            outputs=[set_dropdown, preset_message, gallery, checkpoint_targets] + preset_editor_outputs
        )

        ui_component.load(
            fn=reload_presets,
            inputs=[set_dropdown, folder_filter_dropdown],
            outputs=[set_dropdown, preset_message, gallery, checkpoint_targets] + preset_editor_outputs
        )

    return [(ui_component, "Thumbnailizer", "thumbnailizer_tab")]

script_callbacks.on_ui_tabs(on_ui_tabs)

print ("Thumbnailizer initialized")
